language: "node_js"
node_js:
  - "15"
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"

before_install:
 - "npm install istanbul -g"
 - "npm install coveralls -g"

script: "make ci-travis"

after_success:
  - "make submit-cov-to-coveralls"
